### ISSUE TITLE
Cypher SET Clause for Copying All Properties

### ISSUE THREAD

**Issue by parvit** [parvit/age#2]
Is your feature request related to a problem? Please describe.
Currently, the AGE implementation of the Cypher SET clause expects a variable name.

If a variable name isn't provided, the following error is currently noted:
ERROR: SET clause expects a variable name

This means that if I want to copy all properties from one entity to another, I would need to know all possible properties by name before creating a given query. An example of where copying all properties can be useful is "renaming" a relation in a single query (creating the new, copying the properties, and deleting the old).

Describe the solution you'd like
The same SET syntax [used by Neo4J](https://neo4j.com/docs/cypher-manual/current/clauses/set/#set-copying-properties-between-nodes-and-relationships) and https://github.com/RedisGraph/RedisGraph/pull/2051

Describe alternatives you've considered
Querying all properties in first query, using results from first query to create a second query containing the SET clause.

Additional context
I created a similar request https://github.com/RedisGraph/RedisGraph/issues/2045 last year, and they found it pretty trivial to support.

**Comment by parvit** [comment]
@TropicalPenguin

**Comment by TropicalPenguin** [comment]
Am curious to know @parvit; has this turned out more complex than expected?

**Comment by parvit** [comment]
yeah the main issue is that there seems to be no facilities available for recovering the data of a node at the parser level.

That's because the only data expected in the set target definition are single values so those are resolvable at that level and there's no need for that functionality.

Problem is that the executor of the query target is even more meta about what it does, so its really cryptic and with lots of unclear conversions between the types.

I have some hope that it could be done at that level by specifying a different target but I'm not sure.

I hope in the near future i can find out more but for now i have hit a brick wall.

**Comment by TropicalPenguin** [comment]
Understood. Thank you.

**Comment by parvit** [comment]
Seen the recent developments there's no need for this anymore.
